name: nocode_commons
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  verification_api:
    git:
      url: https://github.com/boodskap/verification_api.git

  nocode_api:
    git:
      url: https://github.com/boodskap/nocode_api.git

  twinned_api:
    git:
      url: https://github.com/boodskap/twinned_api.git

  twinned_widgets:
    git:
      url: https://github.com/boodskap/twinned_widgets.git
#    path:
#      twinned_widgets

  google_fonts: ^5.0.0
  http: ^1.1.0
  community_charts_flutter: ^1.0.2
  fl_chart: ^0.67.0
  provider: ^6.1.1
  colored_json: ^1.1.2
  convex_bottom_bar: ^3.2.0
  custom_date_range_picker: ^1.0.10
  flutter_dotenv: ^5.1.0
  cupertino_icons: ^1.0.2
  column_layout: ^1.0.0
  flutter_spinkit: ^5.2.0
  otp_text_field: ^1.1.3
  device_info_plus: ^10.0.1
  shared_preferences: ^2.2.2
  sizer: ^2.0.15
  uuid: ^4.1.0
  pluto_menu_bar: ^3.0.1
  dropdown_search: ^5.0.6
  flutter_spinbox: ^0.13.1
  eventify: ^1.0.1
  rename_app: ^1.3.1
  number_inc_dec: ^0.8.0
  accordion: ^2.6.0
  flutter_iconpicker: ^3.2.4
  flutter_colorpicker: ^1.0.3
  responsive_framework: ^1.1.1
  animations: ^2.0.7
  loading_gifs: ^0.3.0
  navigation_utils: ^0.4.1
  dotted_border: ^2.1.0
  textfield_search: ^0.10.0
  font_awesome_flutter: ^10.6.0
  dropdown_button2: ^2.3.9
  carousel_slider: ^4.2.1
  dropdown_plus: ^0.0.9
  flutter_slider_drawer_enhanced: ^2.1.6
  intl: ^0.18.1
  pinput: ^4.0.0
  flutter_rating_bar: ^4.0.1
  super_tooltip: ^2.0.7
  progress_dialog_null_safe: ^3.0.0
  file_picker: ^8.0.0+1
  dio: ^5.3.4
  string_validator: ^1.0.2
  flutter_staggered_grid_view: ^0.7.0
  flutter_font_picker: ^1.4.0
  boxy: ^2.1.3
  moment_dart: ^2.0.2
  mqtt5_client: ^4.0.3
  intl_phone_field: ^3.2.0
  synchronized: ^3.1.0+1
  gauge_indicator: ^0.4.3
  gauges: ^1.0.0
  knob_widget: ^1.0.3
  flutter_code_editor: ^0.3.1
  row_layout: ^1.0.2
  get: ^4.6.6
  fluttertoast: ^8.2.4
  flutter_map: ^6.1.0
  flutter_map_cancellable_tile_provider: ^2.0.0
  flutter_map_line_editor: ^6.0.0
  timeago: ^3.6.1
  data_table_2: ^2.5.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  synchronized: ^3.1.0+1

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  assets:
    - assets/images/
